// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxerwifqyskugxdpucdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54ZXJ3aWZxeXNrdWd4ZHB1Y2RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NzAyNzksImV4cCI6MjA2NzE0NjI3OX0.WgUTeXrOXscp7LmtMpU9acvPcg4ZSKSnrXgTNvCT0nY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});